### ISSUE TITLE
Do you have grafana dashboard for https://github.com/Vonng/pg/blob/master/mon/monitoring-improvement.md ? 

### ISSUE THREAD

**Issue by patsevanton** [Vonng/pg#4]
Hello!

Do you have grafana dashboard for https://github.com/Vonng/pg/blob/master/mon/monitoring-improvement.md ?

**Comment by Vonng** [comment]
Thanks for your mail….  That proposal record is obsolete, and … quite sensitive.

I would suggest using this export instead [pg_exporter](https://github.com/Vonng/pg_exporter ) . which could export much more metrics. and allows  you building much fancy dashboard on that.    

I do have a series fancy dashboards for that exporter. I’m quiet proud of the design and willing to share but I’m afraid I couldn’t do that due to business conduct…

but with these metrics and a rough concept model below I guess you could make your own dashboard quickly...

![image](https://user-images.githubusercontent.com/8587410/81652557-8197b680-9466-11ea-9aef-c0ee3ecb1dc3.png)
